#:kivy 1.9
<Contenedor>
    #aqui jala de otro
    lbl:otro
    BoxLayout:
        orientation:'vertical'
        size: root.width, root.height
        Label:
            id:otro
            text:'Resultado de consulta:'

        Button:
            id:boton_envio
            text:"Submit"
            on_press:root.consultar()

        TextInput:
            id:entrada
            hint_text:"Ciudad"
